//
//   Interface Beholder
//
//   Engenharia da computação
//   Escola Politécnica - PUCPR
//   Gabriel Vitor Cezário
//

module DSMComms {

    enum EventEnum {
        TEST,
        NONE,
        HAHA
    };

    enum DataType {
        UNKNOWN,
        ANALOG,
        DIGITAL
    };

    struct Value {
        double storedValue;
        long timestamp;
    };

    typedef sequence<Value> ValSeq;
    typedef sequence<string> StringSeq;

    interface POA_Beholder {

        // operações
        void LogEventAll(in string valor, in EventEnum event);
        
        void getValue(in string valueId, out Value toGetValue, in DataType type);

        void storeValue(in string valueId, in Value toGetValue, in DataType type);
    };

};
