//
//   Interface Beholder
//
//   Engenharia da computação
//   Escola Politécnica - PUCPR
//   Gabriel Vitor Cezário
//

module DSMComms {

    enum EventEnum {
        TEST,
        NONE,
        HAHA
    };

    enum DataType {
        UNKNOWN,
        ANALOG,
        DIGITAL
    };

    struct Value {
        string id;
        double storedValue;
        string timestamp;
        DataType type;
    };

    typedef sequence<Value> ValueSequence;

    interface POA_Beholder {

        // operações
        void LogEventAll(in string valor, in EventEnum event);
        
        void getValue(inout Value toGetValue);

        void storeValue(in Value toSetValue);
    };

};
