//
//   Interface Beholder
//
//   Engenharia da computação
//   Escola Politécnica - PUCPR
//   Gabriel Vitor Cezário
//

module DSMComms {

    enum EventEnum {
        TEST,
        NONE,
        HAHA
    };

    enum DataType {
        UNKNOWN,
        ANALOG,
        DIGITAL
    };

    struct Value {
        string id;
        double storedValue;
        long timestamp;
        DataType type;
    };

    typedef sequence<Value> ValueSequence;
    typedef sequence<string> idSequence;

    interface POA_Beholder {

        // operações
        void LogEventAll(in string valor, in EventEnum event);
        
        void getValue(in string valueId, inout ValueSequence toGetValues);

        void storeValue(in idSequence valueId, in ValueSequence toSetValue);
    };

};
