//
//   Interface Beholder
//
//   Engenharia da computação
//   Escola Politécnica - PUCPR
//   Gabriel Vitor Cezário
//

exception SaldoInsuficiente {};

module LOG {
enum EventType {TEST, NONE, HAHA};
}

interface Beholder {

    // operações
    void LogEventAll(in string valor, in LOG::EventType event);

};
