/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This code was generated by avrogencpp 1.11.2. Do not edit.*/

#ifndef DIGITALDATA_HH_2453724051_H
#define DIGITALDATA_HH_2453724051_H


#include <sstream>
#include <any>
#include "avro/Specific.hh"
#include "avro/Encoder.hh"
#include "avro/Decoder.hh"

namespace c {
struct Digital {
    int32_t value;
    int32_t quality;
    std::string timestamp;
    Digital() :
        value(int32_t()),
        quality(int32_t()),
        timestamp(std::string())
        { }
};

}
namespace avro {
template<> struct codec_traits<c::Digital> {
    static void encode(Encoder& e, const c::Digital& v) {
        avro::encode(e, v.value);
        avro::encode(e, v.quality);
        avro::encode(e, v.timestamp);
    }
    static void decode(Decoder& d, c::Digital& v) {
        if (avro::ResolvingDecoder *rd =
            dynamic_cast<avro::ResolvingDecoder *>(&d)) {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (std::vector<size_t>::const_iterator it = fo.begin();
                it != fo.end(); ++it) {
                switch (*it) {
                case 0:
                    avro::decode(d, v.value);
                    break;
                case 1:
                    avro::decode(d, v.quality);
                    break;
                case 2:
                    avro::decode(d, v.timestamp);
                    break;
                default:
                    break;
                }
            }
        } else {
            avro::decode(d, v.value);
            avro::decode(d, v.quality);
            avro::decode(d, v.timestamp);
        }
    }
};

}
#endif
